
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://localhost:8761}/eureka/

security:
  oauth2:
    client:
      accessTokenUri: http://${AUTH_HOST:${HOST:localhost}}:${AUTH_PORT:8760}/oauth/token
      userAuthorizationUri: http://${AUTH_HOST:${HOST:localhost}}:${AUTH_PORT:8760}/oauth/authorize
      tokenName: oauth_token
    resource:
      tokenInfoUri: http://${AUTH_HOST:${HOST:localhost}}:${AUTH_PORT:8760}/oauth/check_token