CONFIG_SERVER_URL: https://emn-cloud-config.herokuapp.com
EUREKA_SERVER_URL: https://emn-cloud-eureka.herokuapp.com/ 
AUTH_SERVER_URL: https://emn-cloud-auth.herokuapp.com
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761}/eureka/

security:
  oauth2:
    client:
      accessTokenUri: ${AUTH_SERVER_URL:http://${AUTH_HOST:${HOST:localhost}}:${AUTH_PORT:8760}}/oauth/token
      userAuthorizationUri: ${AUTH_SERVER_URL:http://${AUTH_HOST:${HOST:localhost}}:${AUTH_PORT:8760}}/oauth/authorize
      tokenName: oauth_token
    resource:
      tokenInfoUri: ${AUTH_SERVER_URL:http://${AUTH_HOST:${HOST:localhost}}:${AUTH_PORT:8760}}/oauth/check_token
